language: elixir
elixir:
  - 1.3.4
  - 1.4.5
  - 1.5.2
otp_release:
  - 18.3
  - 19.3
  - 20.0
script:
  - MIX_ENV=test mix do deps.get, compile, coveralls.travis
matrix:
  exclude:
  - elixir: 1.3.4
    otp_release: 20.0
